### ISSUE TITLE
Default DAO Buider

### ISSUE THREAD

**Issue by shepheb** [foam-framework/foam#103]
_From [k...@chromium.org](https://code.google.com/u/101260952816761938100/) on November 19, 2013 16:58:22_

Create a 'default DAO' builder which builds a DAO from a Model.
Index information should be added to the Model and automatically added to DAO's which accept Index information.
Model Relationship information should be used for creating referential integrity DAO decorators.
The type of 'default' DAO to be generated should be configurable with a factory.

_Original issue: http://code.google.com/p/foam-framework/issues/detail?id=103_

**Comment by jacksonic** [comment]
foam.apps.AppBuilder is using DAOFactory to store info and create a DAO based on it. A default DAO builder would be a useful extension for more complicated cases with more than one model to store.

**Comment by shepheb** [comment]
Is this still something we want to do? It seems relevant to AppBuilder, so I'm assigning to @jacksonic for triage and maybe implementation.

**Comment by jacksonic** [comment]
We don't need it for AppBuilder's current roadmap. It would be a nice-to-have at some future point.
