### ISSUE TITLE
Add 'state' property to AbstractView

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam#225]
Add a 'state' property to AbstractView which tracks the View's initialization state.

States should include (maybe):
   - initial: when the object has been created but not yet rendered
   - rendered: when the object has had it's toHTML() method called but before initHTML() is called
   - initialized: after initHTML() is called
   - orphaned: the View's element has been removed from the DOM
   - destroyed: the View's destroy() method has been called

This is needed to avoid trying to update the DOM before it has been added to document or after it has been orphaned or removed.

Also, this could be used to unify the on/addEventListener and AbstractView.setClass/DOM.setClass methods which are equivalent but one is before the View has been initialized and one is for after.

**Comment by shepheb** [comment]
Replaced by the U2 view lifecycle and virtual DOM, and to a lesser extent the U1 view lifecycle.
