### ISSUE TITLE
Changing Model of DetailView doesn't hide old ActionButtons

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam#243]
FUN:DetailViewSwitchModelWithShowActions reveals the bug.

**Comment by shepheb** [comment]
@adamvy is this still relevant? It was a bug in Quickbug, but it has implications for `DetailView`.

**Comment by adamvy** [comment]
I doubt it.

We have a whole new DV with U2 that will or does handle this properly.

**Comment by kgrgreer** [comment]
Fixed in U2.
