### ISSUE TITLE
Property names should be able to have '_' in them.

### ISSUE THREAD

**Issue by dj2** [foam-framework/foam#262]
I created a property called 'created_on' when I tried to use the Note.CREATED_ON I received:
Uncaught TypeError: Cannot read property 'deepClone' of undefined 

From the console:

'foo_bar'.constantize()
"FOO__BAR"

**Comment by jlhughes** [comment]
The following constantize change provides support for property names with _ in them. 

@@ -379,7 +379,7 @@ var constantize = memoize1(function(str) {
   // TODO: add property to specify constantization. For now catch special case to avoid conflict with context this.X and this.Y.
   if ( str === 'x' ) return 'X_';
   if ( str === 'y' ) return 'Y_';
-  return str.replace(/[a-z_][^0-9a-z_]/g, function(a) {
+  return str.replace(/[a-z][^0-9a-z_]/g, function(a) {
     return a.substring(0,1) + '_' + a.substring(1,2);
   }).toUpperCase();
 });

**Comment by kgrgreer** [comment]
constantize fixed, thx
