### ISSUE TITLE
Internet Explorer Compatibility

### ISSUE THREAD

**Issue by Fadingwhite** [foam-framework/foam#323]
IE is giving an error "Object doesn't support this action" in ModelDAO at around line 30:
var foamdir = new URL(window.FOAM_BOOT_DIR).pathname;

**Comment by kgrgreer** [comment]
It looks like it is actually the line just before that one.  IE doesn't appear to have the .location property on window, but instead uses .url.  I'll have to find a windows machine to test on.  Thanks

**Comment by kgrgreer** [comment]
What version of IE are you using?  Thanks

**Comment by Fadingwhite** [comment]
IE 11 Version 11.0.9600.17959

**Comment by shepheb** [comment]
Marking as check-repro - we should review IE compatibility periodically anyway.

**Comment by shepheb** [comment]
IE11 is broken, failing to load `foam.ui.View`, among other things.

**Comment by jacksonic** [comment]
There's an ie11 branch that had some fixes on it, not sure if it didn't get
merged somehow? I'll have to check.

**Comment by shepheb** [comment]
Adam and I fixed this after you left. Should be good on master. I'm going
to check Edge on Windows 10 tomorrow morning.

**Comment by shepheb** [comment]
Working nicely in IE11 and Edge. (Tested using Microsoft's VMs, Win8.1+IE11 and Win10+Edge.)
