### ISSUE TITLE
mlang compile_(a) doesn't handle null a

### ISSUE THREAD

**Issue by jlhughes** [foam-framework/foam#326]
foam (master) git revision: f01aaf3

The stack trace is from a 'built' foam.js so the line numbers are meaningless, but it maps to:

mlang.js:22
function compile_(a) {
  return /*Expr.isInstance(a) || Property.isInstance(a)*/ a.f ? a :
    a === true  ? TRUE        :
    a === false ? FALSE       :
    ConstantExpr.create({arg1:a});
}

Generating: Uncaught TypeError: Cannot read property 'f' of undefined
compile_ @ jbbfc__sefoam_js:13999
CONTAINS @ jbbfc__sefoam_js:16063
CLASS.actions.action @ jbbfc__sefoam_js:19570
CLASS.methods.maybeCall @ jbbfc__sefoam_js:9638
(anonymous function) @ jbbfc__sefoam_js:6249
init @ jbbfc__sefoam_js:19739
f @ jbbfc__sefoam_js:6022
FObject.create @ jbbfc__sefoam_js:5333
BootstrapModel.create @ jbbfc__sefoam_js:6475
(anonymous function) @ jbbfc__sefoam_js:11913
MODEL.methods.simpleBind @ jbbfc__sefoam_js:846
ajoin @ jbbfc__sefoam_js:1636
get @ jbbfc__sefoam_js:1330
(anonymous function) @ jbbfc__sefoam_js:1641
(anonymous function) @ jbbfc__sefoam_js:1146
CLASS.methods.install @ jbbfc__sefoam_js:11954
CLASS.methods.init @ jbbfc__sefoam_js:11888
...
DOM.init

**Comment by kgrgreer** [comment]
Try replacing a.f with "a && a.f", and see if that works.  I'm not sure we
intended to allow for null values, so you might have issues further down
the line as well.  Let me know if this works or if you have further
problems.

**Comment by jlhughes** [comment]
Yes, a test of 'a' is my current fix. I highly suspect I have other issues.
I'll report again without the fix when I'm more confident of my side.
Thanks
Joel

**Comment by jlhughes** [comment]
The root cause was invalid data in our app, now that everything is working, this 'fix' is no longer required.
