### ISSUE TITLE
FlexTableView uses classes on `document.body` to signal local state

### ISSUE THREAD

**Issue by shepheb** [foam-framework/foam#334]
The `initGlobalState` method sets up a class to toggle on resizing state. If this class is necessary (used to show all the dividers while resizing?) it should be toggled on the table's own container `div`, not the document body. That would make multiple tables, no matter their nesting, display differently when any one of them is resized.

**Comment by mdittmer** [comment]
This is applied globally for UX reasons. It ensures that the resize cursor is always shown while the user clicks and drags the handle. Without a document-body-level CSS rule, the cursor flips between the resize cursor and the default cursor as the resize handle lags behind the movement of the cursor.

**Comment by adamvy** [comment]
Where is the class you're setting defined?  I tried searching for it and
didn't find it.

Also this isn't the best way to do this.  We should put an ID on body just
to use setClass().  Instead I would use this.X.dynamic(function() {
self.isResizing; }, function() { DOM.setClass(self.document.body,
'resizing'); });

**Comment by adamvy** [comment]
Sorry we *shouldn't* but an id on body just to use setClass()

**Comment by mdittmer** [comment]
Fixed with use of DOM.setClass() instead.
