### ISSUE TITLE
FOAM By Example page not functioning

### ISSUE THREAD

**Issue by brendan** [foam-framework/foam#335]
http://foam-framework.github.io/foam/foam/index.html?model=foam.flow.FOAMByExample

Javascript console shows:
Unknown element name: "book-title"
FObject.js:358 Unknown element name: "section" (25 times)

This looks broken to me?

**Comment by kgrgreer** [comment]
Thanks for catching this.  We'll fix.

**Comment by mdittmer** [comment]
This issue is now fixed on master. We'll close the issue once github.io has been updated.

**Comment by kgrgreer** [comment]
I'll push to github tomorrow after I finish some other changes that I'm working on that I also need to push.
