### ISSUE TITLE
Setting 'label' on GroupBySearchView broken with commit 9016b01

### ISSUE THREAD

**Issue by jlhughes** [foam-framework/foam#352]
The change in commit https://github.com/foam-framework/foam/commit/9016b01453a18084419598a33586cd3a11c07a57 breaks setting 'label' on GroupBySearchView and GroupByMultiSearchView.

ex: this.GroupBySearchView.create({...., label: 'Some Label'})

**Comment by shepheb** [comment]
That seems strange, since it didn't change either way the passing through of `label`. Have you tried both settings of `floatingLabel`?

**Comment by jlhughes** [comment]
Believe the issue is elsewhere but it's hard to pin down as this commit is in the middle of a bunch that are dependent. I'll close this and keep trying to figure out what broke it.

**Comment by jlhughes** [comment]
It's something in here: https://github.com/foam-framework/foam/commit/e8c1a1864af9e9660393a5fa04d143f341288e30
Working through each change.  If there is something that catches your eye that I can test, let me know.

**Comment by jlhughes** [comment]
Working at https://github.com/foam-framework/foam/commit/77f2fadef17c0cccb6cd8add163113fd1227e88c
I undid the changes to SearchMgr, GroupBySearchView, TextFieldView - no change. 
I'll undo the others but they really don't seem relevant.

**Comment by jlhughes** [comment]
Resolved with https://github.com/foam-framework/foam/commit/2fb844dadee6345379c154ccb86456b59fa9bd10
