### ISSUE TITLE
Going forward then back and canceling in wizards does not remove tentatively put() item from DAO

### ISSUE THREAD

**Issue by mdittmer** [foam-framework/foam#368]
Clicking "CANCEL" in wizards should result in no new apps appearing in the associated app DAO.

**Comment by jacksonic** [comment]
Opening the model edit wizard in an existing app and cancelling it now deletes the app!

And a bigger question: at which point in the wizard has the user done enough work to keep the partially defined app? Getting to the last screen and accidentally clicking outside the wizard shouldn't cost the user anything.

**Comment by mdittmer** [comment]
In that case, the wizard should not be cancelable by clicking outside.
Cancel should actually cancel App creation though.

**Comment by jacksonic** [comment]
Only AppWizards (as in the first page of an app creation wizard) should delete the app on cancel. Other cases of model and dao selection would need to do nothing, or maybe roll back model/dao changes.
