### ISSUE TITLE
New-or-existing wizard with no choice selected should have default next label "Next", not "Finish"

### ISSUE THREAD

**Issue by mdittmer** [foam-framework/foam#369]
User cannot "Finish" wizard from new-or-existing step. This step always precedes new item setup or exiting item setup.

**Comment by jacksonic** [comment]
Picking a DAO type that requires no configuration, or picking an existing model, do not have a subsequent step. The text "finish" should show up iff the next page is null. If you don't want that showing up, make sure to initialize the next page to one of the choices available.

**Comment by mdittmer** [comment]
The current configuration of kiosk apps has a default selection. Closing this again.
