### ISSUE TITLE
Wizards need to be more robust

### ISSUE THREAD

**Issue by mdittmer** [foam-framework/foam#374]
Spamming wizard next/back buttons with clicks causes stack and button wiring to break. Symptoms include buttons stop working entirely, and "CANCEL" button (after going forward then coming back) doesn't work.

The latter symptom appears to occur because the stack erroneously winds up with two views on it, despite that the first-wizard-page-view is being show; this causes isAvailable() to return false, so maybeCall() never activates the action.

**Comment by jacksonic** [comment]
I'm going to guess this is from the transitions between pages leaving multiple buttons available for clicking. The pages will have to better track which one is actually visible.
