### ISSUE TITLE
Add embedded graphs to SyncManager

### ISSUE THREAD

**Issue by shepheb** [foam-framework/foam#44]
_From [k...@chromium.org](https://code.google.com/u/101260952816761938100/) on November 06, 2013 09:22:42_

Cr2bug currently shows graphs for sync # of updates and bandwidth use.  These should be made generic and embedded into the SyncManager model.

_Original issue: http://code.google.com/p/foam-framework/issues/detail?id=44_

**Comment by shepheb** [comment]
Is this still relevant?

**Comment by kgrgreer** [comment]
obsolete
