### ISSUE TITLE
Somehow "order" is a special name that cannot be added to a property

### ISSUE THREAD

**Issue by mdittmer** [foam-framework/foam#466]
It is not clear yet how widespread this issue is. It first appeared in a model inheriting from foam.u2.View, but since u2 doesn't appear to mention 'order' anywhere, it is suspected that the problem runs deeper.

To reproduce:

Create a subclass of foam.u2.View and give it a property with name:'order', and a defaultValue, or factory, or similar. In the init method, observe that the defaultValue/factory/... is not being honored.

**Comment by shepheb** [comment]
Does this have anything to do with `foam.mlang.CannedQuery.order`?

**Comment by mdittmer** [comment]
I can no longer reproduce this bug.
