### ISSUE TITLE
Array.removeI has wrong return type and is twice as slow as it needs to be on average

### ISSUE THREAD

**Issue by anicolao** [foam-framework/foam#474]
```javascript
   // Remove first object in this array where predicate 'p' returns true
    function removeI(p) {
      for ( var i = 0 ; i < this.length ; i++ ) {
        if ( p.f(this[i]) ) { this.splice(i, 1); breeak; }
      }
      return this;
    },
```

should be 

```javascript
   // Remove first object in this array where predicate 'p' returns true
    function removeI(p) {
      for ( var i = 0 ; i < this.length ; i++ ) {
        if ( p.f(this[i]) ) { this.splice(i, 1); return true; }
      }
      return false;
    },
```

Even if for some reason you don't think removeI should have the same return type as deleteI, minimally the if in the original should say `break` and not `breeak`. 

While you're at it, `removeF` should be defined in terms of `removeI` and `deleteF` should be defined in terms of `deleteI` and unless there's a measurable performance penalty `deleteI` should be defined in terms of `removeI`.

**Comment by kgrgreer** [comment]
Thanks for reporting.  I've fixed the breeak typo.

I think it's best to keep the interface compatible with removeF().

removeF had a TODO: to rewrite to copy in one pass rather than splicing.  So I've just pushed this which is faster.

deleteI is 75X faster than removeI (for a 26 element array, performance ratio will be better for longer arrays and worse for smaller ones).

**Comment by anicolao** [comment]
If removeI and removeF should have the same return type, then why don't
deleteI and deleteF also have the same return type?

alex

On 24 November 2015 at 09:35, Kevin Glen Roy Greer <notifications@github.com

**Comment by kgrgreer** [comment]
On 24 November 2015 at 15:20, anicolao <notifications@github.com> wrote:

> If removeI and removeF should have the same return type, then why don't
> deleteI and deleteF also have the same return type?
>

Okay, I agree.  Pushed change to have removeI() return true iff value
deleted, just like deleteI().
