### ISSUE TITLE
U2 Browser: Race condition when immediately creating a new entry

### ISSUE THREAD

**Issue by shepheb** [foam-framework/foam#495]
1. Create a new entry.
2. Enter text into an input field.
3. Do **not** blur the field.
4. Click the checkmark to save the new entry.

Observe that the new row in the list is blank, and then fills in. If your DAO persists, and you reload, you'll see that the value was never set in the persistent DAO.

Probably this can be solved by delaying the `ObjectReplicator` calling `put()` slightly.

**Comment by adamvy** [comment]
I thought that the ObjectReplicator was not used in the DAOCreateController.

The ObjectReplicator listener should probably be merged to 100ms or so, such that rapid object changes don't hammer the DAO.

But even if that fixes the problem, that feels like a hackish fix.  Something not dependant upon timeouts would be more robust.
