### ISSUE TITLE
Fix u2.Select Design

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam#506]
Select was just meant to be a wrapper for the raw <select> tag, but with 'data' binding.  It is now a ChoiceView, which was not the intent.

Revert Select to just a simple select tag and make a new ChoiceView to replace it.  Probably move tag-level elements like Select and Input to a 'tag' sub-package.

ChoiceViewTrait requires that it's users be u2.View's, so it should just be an AbstractChoiceView instead as this will avoid user-error of trying to use it in Elements.

@shepheb @adamvy

**Comment by shepheb** [comment]
See #510.

**Comment by shepheb** [comment]
Done by #510 and 71db38bbd9.
