### ISSUE TITLE
Bower package is at 0.3.1 - please update with 0.5.0

### ISSUE THREAD

**Issue by psperneac** [foam-framework/foam#526]
While the npm released version is 0.5.0, the bower package is still at 0.3.1 (https://libraries.io/bower/foam). The bower package is more interesting as it is the one-file variety. Please update/upload a new bower package

**Comment by shepheb** [comment]
Now Bower has the same 0.5.0 that npm has. Note that both are somewhat behind master, but that might be a feature if that version works for you.
