### ISSUE TITLE
Does Foam have many external dependencies?

### ISSUE THREAD

**Issue by Kentoseth** [foam-framework/foam#544]
I found this package.json here:

https://github.com/foam-framework/foam/blob/d917104590005ad22308fe8f27e75ef6c6838136/apps/todo/package.json

and it looks like Foam does not have many external dependencies.

If it does, can you please explain how it relies on such dependencies (eg. which libs does it depend on from the npm registry & how they are called)?

**Comment by adamvy** [comment]
FOAM has no external dependencies.  That package.json is only for the TodoMVC demo app, which has some dependencies other than FOAM.
