### ISSUE TITLE
FOAM By Example CSS is broken (hiding ansers

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam#545]
http://foam-framework.github.io/foam/foam/index.html?model=foam.flow.FOAMByExample

**Comment by kgrgreer** [comment]
Actually, I don't think it's a CSS issue.  The content seems to be missing from the views.

**Comment by jacksonic** [comment]
Yes, the code isn't being loaded as a proper flow element, just a string. Looking into it...

**Comment by jacksonic** [comment]
The problem is from an overloading of what Property.type means in flow elements, which is incompatible with current type-as-property-model usage. I'll change flow elements to work with something other than 'type'
