### ISSUE TITLE
FOAMByExample - MDAO not defined

### ISSUE THREAD

**Issue by bartonhammond** [foam-framework/foam#553]
All ```3. DAOs (FOAM Classes)``` fail due to ```X.arequire('MDAO'),``` is ```undefined```

<img width="1440" alt="screen shot 2016-03-31 at 11 17 51 am" src="https://cloud.githubusercontent.com/assets/1282364/14182790/9898a45a-f732-11e5-9353-df4c5478ba64.png">

See error:
<img width="1317" alt="screen shot 2016-03-31 at 11 23 31 am" src="https://cloud.githubusercontent.com/assets/1282364/14182920/3f3f3238-f733-11e5-8931-50615eaa3c8c.png">

**Comment by kgrgreer** [comment]
Fixed.  Thanks for reporting.
