### ISSUE TITLE
TODO app doesn't work

### ISSUE THREAD

**Issue by jots** [foam-framework/foam#557]
Following along from:
http://foam-framework.github.io/foam/tutorial/todo/0-intro/
I:
```
git clone https://github.com/foam-framework/foam.git
python -m SimpleHTTPServer
go to:
http://localhost:8000/foam/index.html?model_=foam.tutorials.todo.TodoApp
```
The page comes up, but I hit the "+" enter some text into the title field, hit enter and nothing happens.  Can't figure out how to add a TODO.   Also went on to the next step of the tutorial and had the same problem.  Using  chrome version 49.0.2623.56 beta (64-bit) on linux.

I don't see any errors in the console.  What am I missing?

**Comment by kgrgreer** [comment]
Once you've edited the TODO, you click on the checkmark in the top-right corner to save it.
Just hitting enter to save is a good idea for this app.

**Comment by jots** [comment]
Thank you Kevin  That works.  feeling a little sheepish right now :-)
Looking forward to trying out Foam.  I saw your presentation to #fstoconf15 on youtube today and was very impressed!

**Comment by kgrgreer** [comment]
Thanks!  There are more videos at:
https://www.youtube.com/channel/UCUmJgdncsCyHO3YAfsk2Kjg

If you have any issues or questions, please let us know at
foam-framework-discuss@googlegroups.com
