### ISSUE TITLE
ValueProperty

### ISSUE THREAD

**Issue by shepheb** [foam-framework/foam#82]
_From [k...@chromium.org](https://code.google.com/u/101260952816761938100/) on November 14, 2013 14:41:30_

Create a new ValueProperty type which supports 'onValueChange' property.
The purpose of this property is to provide a callback when either the Value's value changes, or when the Value changes.

_Original issue: http://code.google.com/p/foam-framework/issues/detail?id=82_

**Comment by shepheb** [comment]
This might make a good counterpart to `DAOProperty`, which has a similar `onDAOUpdate`.

@kgrgreer , thoughts?

**Comment by kgrgreer** [comment]
Obsolete.  We don't use Values directly since we added value$ support.
